# Generated by Django 2.2.2 on 2019-06-16 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdk', '0004_auto_20190616_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default='1234567890'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 16, 8, 18, 54, 994851), max_length=8),
        ),
        migrations.AlterField(
            model_name='signup',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 16, 8, 18, 54, 993346)),
        ),
    ]
