# Generated by Django 2.2 on 2019-06-19 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdk', '0019_auto_20190619_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 13, 22, 24, 385033), max_length=8),
        ),
        migrations.AlterField(
            model_name='signup',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 19, 13, 22, 24, 380027)),
        ),
    ]
