# Generated by Django 2.2.2 on 2019-06-20 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdk', '0022_auto_20190620_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2019, 6, 20, 9, 45, 1, 527222), max_length=8),
        ),
        migrations.AlterField(
            model_name='signup',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 20, 9, 45, 1, 518206)),
        ),
    ]
