# Generated by Django 2.2.2 on 2019-06-21 07:48

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdk', '0028_auto_20190620_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Follow',
        ),
        migrations.AddField(
            model_name='profile',
            name='Follower',
            field=models.ManyToManyField(blank=True, related_name='Follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='Following',
            field=models.ManyToManyField(blank=True, related_name='Following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signup',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 21, 13, 18, 46, 233754)),
        ),
    ]
