# Generated by Django 2.2.2 on 2019-06-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_remove_user_following'),
        ('sdk', '0030_auto_20190622_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
